### ISSUE TITLE
App is not detecting error

### ISSUE THREAD

**Issue by soichih** [brainlife/app-rsHRF#4]
I accidentally fed incorrect mask file, and rsHRF failed but App was marked as "success". I believe rsHRF is not setting a correct exit code.

```
The dimension of your mask is different than the one of your fMRI data!
```

@madhur-tandon @danielemarinazzo Please let me know if you have any insight as to why rsHRF is not returning a non-0 exist code.

**Comment by danielemarinazzo** [comment]
Dear @soichih , thanks for raising this issue! The problem (my responsibility) is that the python experts working on the python version of the app (cc-ing @AmoghJohri too) , do not have neuroimaging expertise, and vice versa. If you have time and will to see where the problem might be, please send a PR. Otherwise I'll try to have this looked into as soon as I can.
Btw are you using the current version?

thanks!

d.

**Comment by AmoghJohri** [comment]
Dear @soichih, thank you for your interest in our app. The issue has been addressed in the current release. You might want to check it out [here](https://pypi.org/project/rsHRF/).
Warm regards,
Amogh Johri

**Comment by soichih** [comment]
@AmoghJohri Thank you for fixing this problem!

I don't see version 1.2.1 released on https://hub.docker.com/r/bids/rshrf/tags yet, but once it's released I will update our script to use v1.2.1 and test it on our end.

**Comment by madhur-tandon** [comment]
Thanks @AmoghJohri for implementing the suggested fix.

Also, @soichih instead of manually changing tags to the version numbers aka `1.2.1` in this case, you could just use the `latest` tag.

You won't have to worry about changing the version numbers in the future. This is because with every new release, the image in the `latest` tag is also updated.

So both `1.2.1` and `latest` will have the same images as of this moment.

**Comment by soichih** [comment]
@AmoghJohri I've tried the 1.2.1 version but I am still having the same issue. rsHRF ended with this error message

> The dimension of your mask is different than the one of your fMRI data!

But it returned exit code 0, so our system couldn't determine that the algorithm failed.

I am running it with the following command line
> singularity exec -e docker://bids/rshrf:1.2.1 rsHRF --input_file ../5f2dc3d3a5b6437164a3ba88/5e62a307215aa2e65175fadb/bold.nii.gz results --atlas ../5f2dc3d3a5b6437164a3ba88/5e7926ace4b2fa07b4491589/mask.nii.gz --estimation canon2dd

@madhur-tandon Thanks for the suggestion! In our case, though, we prefer to use specific tag so that our code can be more deterministic - as we version our code and preserve provenance information in our database. If a user try to rerun the same App, we want the output to be as close as possible to the original output.

**Comment by AmoghJohri** [comment]
Dear @soichih , thank you for pointing that out, the docker container for v1.2.1 seems to correspond for an earlier build. That has been fixed in v1.2.2. 
Also, there are a few changes that have been made w.r.t previous versions, you might slightly need to modify your syntax appropriately (for example: the output-directory has been made a keyword argument instead of a positional one, so you should supply '--output_dir results' instead of just 'results'. 
For all the changes, and additional features, visit [here](https://pypi.org/project/rsHRF/).

**Comment by danielemarinazzo** [comment]
Dear @soichih, we have a new version up. Would you like to give it a go on brainlife?
Thanks!

**Comment by soichih** [comment]
I am testing bids/rshrf:1.3.9 container now > https://brainlife.io/project/5e28c8752f45e286ba090737/process/5fb57732507985c9d1db5a0a

**Comment by danielemarinazzo** [comment]
Dear Soichi

the app and the docker received another major update a couple of months ago.
Do the brainlife apps automatically follow the docker updates, or shall we
inform you every time we change something?

thanks!

**Comment by soichih** [comment]
Yes, we need to update it manually. The App is currently hardcoded to use `docker://bids/rshrf:1.0.8` container

> https://github.com/brainlife/app-rsHRF/blob/1.0.8/main#L16

So someone needs to update this to point to the latest release, right? We should also test the new container on brainlife and make a new release (create a new branch) for this App, and lastly update the App registered on brainlife to use the new branch.

We can do it, but if you prefer doing it yourself, we can transfer this repo to somewhere you will have write access to - and I can walk you through the steps. What do you prefer?

**Comment by danielemarinazzo** [comment]
Dear Soichi

The easiest and foolproof way would be that you do it.
Please let us know if there's something we can do at this point.

Thanks a lot for the continued effort and the great resource.

**Comment by soichih** [comment]
OK. We will take care of it!

CC-ing @giulia-berto

**Comment by giulia-berto** [comment]
I can make a new branch pulling from the latest docker bids/rshrf:1.5.7. Can you give me writing access @soichih?

**Comment by giulia-berto** [comment]
I released a new branch for the App called 1.5.7 using that version, feel free to test it (under advanced, just select that branch)

**Comment by danielemarinazzo** [comment]
Thanks Giulia

even if I select the correct branch in "advanced" the options for rsHRF
estimation in the previous window are still the ones of the old version
(canon2dd, FIR, sFIR), while the new version has other options available.
Is there a way to fix this on your hand, or shall we do something to make
the options explicit/visible to brainlife?

**Comment by giulia-berto** [comment]
Hi Daniele, usually changes to the App are done by the App maintainer. I guess you or @soichih maintains this App?! I cannot edit it unless you give me write permissions. It should be straightforward to make that change though.

**Comment by danielemarinazzo** [comment]
Hi Giulia, thanks a lot! I never got to make this change before, but by just looking at it it seems very easy indeed! We'll do it on our side.

**Comment by giulia-berto** [comment]
Here you can read more: https://brainlife.io/docs/apps/register/. Should you have any issue, feel free to reach out!
